#!/usr/bin/env bash
# Script to install and configure Nginx with a custom HTTP header

sudo apt update -y
sudo apt install -y nginx

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    server_name _;

    location / {
        add_header X-Served-By \$hostname always;
        try_files \$uri \$uri/ =404;
    }
}
EOL

sudo systemctl restart nginx
