#!/usr/bin/env bash
# Script to install and configure HAProxy on Ubuntu

# Update system
sudo apt update -y && sudo apt upgrade -y

# Install HAProxy
sudo apt install -y haproxy

# Backup default HAProxy config
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    option httplog
    option dontlognull
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 100.25.103.0:80 check
    server web-02 100.26.170.186:80 check
EOL

# Restart and enable HAProxy
sudo systemctl restart haproxy
sudo systemctl enable haproxy

# Verify HAProxy status
sudo systemctl status haproxy --no-pager
