#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080

apt update
apt install -y nginx
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/log/nginx /var/lib/nginx
service nginx restart
